http.host: "0.0.0.0"
xpack.monitoring.enabled: false

# 管道设置
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# 日志设置
log.level: info
path.logs: /var/log/logstash

# 配置重载
config.reload.automatic: true
config.reload.interval: 3s

# 死信队列
dead_letter_queue.enable: true
path.dead_letter_queue: /var/lib/logstash/dead_letter_queue
