# 🔧 RedFire配置管理服务 - 开发环境配置示例

# 应用基础配置
app_name: "RedFire Config Service"
app_version: "1.0.0"
environment: "development"
debug: true
host: "0.0.0.0"
port: 8001
workers: 1
log_level: "INFO"

# 数据库配置
database:
  engine: "postgresql"
  host: "localhost"
  port: 5432
  database: "redfire_config"
  username: "redfire"
  password: "redfire123"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  echo_pool: false
  pool_pre_ping: true
  ssl_mode: "prefer"

# Redis配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  max_connections: 50
  retry_on_timeout: true
  socket_timeout: 5.0
  socket_connect_timeout: 5.0
  socket_keepalive: true
  cluster_mode: false
  encoding: "utf-8"
  decode_responses: true
  ssl: false

# VnPy配置
vnpy:
  log_level: "INFO"
  data_path: "./vnpy_data"
  temp_path: "./vnpy_temp"
  strategy_path: "./strategies"
  strategy_data_path: "./strategy_data"
  tick_data_enabled: true
  bar_data_enabled: true
  event_queue_size: 100000
  worker_threads: 4
  
  # 网关配置示例
  gateways:
    - name: "CTP"
      class_name: "CtpGateway"
      enabled: true
      host: "180.168.146.187"
      port: 10130
      timeout: 30
      retry_count: 3
      retry_interval: 5
      extra_config:
        product_info: "RedFire"
        auth_code: ""
    
    - name: "Binance"
      class_name: "BinanceGateway"
      enabled: false
      timeout: 30
      retry_count: 3
      retry_interval: 5
      extra_config:
        testnet: true

# 安全配置
security:
  secret_key: "your-super-secret-jwt-key-must-be-at-least-32-characters-long"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  
  # CORS配置
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:8080"
  cors_methods: ["*"]
  cors_headers: ["*"]
  cors_credentials: true
  
  # 速率限制
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 60
  
  # 密码配置
  password_hash_algorithm: "bcrypt"
  password_salt_rounds: 12
  
  # SSL配置
  ssl_enabled: false

# 监控配置
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  log_level: "INFO"
  log_rotation: true
  log_max_size: "100MB"
  log_backup_count: 5
  
  # Prometheus配置
  prometheus:
    enabled: true
    host: "localhost"
    port: 9090
    scrape_interval: "15s"
    evaluation_interval: "15s"
  
  # Grafana配置
  grafana:
    enabled: true
    host: "localhost"
    port: 3000
    admin_user: "admin"
    admin_password: "admin"
  
  # 告警配置
  alerting_enabled: false
  email_enabled: false

# API网关配置
api_gateway:
  host: "0.0.0.0"
  port: 8080
  workers: 4
  api_prefix: "/api"
  api_version: "v1"
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"
  request_timeout: 30
  keep_alive_timeout: 5
  max_request_size: 16777216  # 16MB
  max_concurrent_requests: 1000
  
  # 服务发现
  service_discovery_enabled: true
  consul_host: "localhost"
  consul_port: 8500
  
  # 负载均衡
  load_balancer_algorithm: "round_robin"
  health_check_interval: 30

# 扩展配置
extra_config:
  # 可以在这里添加自定义配置
  custom_feature_enabled: true
  custom_timeout: 300
  custom_settings:
    feature_a: "enabled"
    feature_b: "disabled"
    max_retries: 3
