"""
系统级常量定义
==============

定义系统运行相关的常量
"""

# 分页相关
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 1000
MIN_PAGE_SIZE = 1

# 超时设置（秒）
DEFAULT_TIMEOUT = 30
DEFAULT_CONNECTION_TIMEOUT = 10
DEFAULT_READ_TIMEOUT = 30
DEFAULT_WRITE_TIMEOUT = 30

# 重试设置
MAX_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY = 1  # 秒
EXPONENTIAL_BACKOFF_MULTIPLIER = 2

# 服务相关
SERVICE_HEALTH_CHECK_INTERVAL = 30  # 秒
SERVICE_START_TIMEOUT = 60  # 秒
SERVICE_STOP_TIMEOUT = 30  # 秒

# 缓存相关
DEFAULT_CACHE_TTL = 300  # 5分钟
SHORT_CACHE_TTL = 60     # 1分钟
LONG_CACHE_TTL = 3600    # 1小时

# 数据库相关
DEFAULT_DB_POOL_SIZE = 10
MAX_DB_POOL_SIZE = 50
DB_POOL_OVERFLOW = 20
DB_POOL_TIMEOUT = 30

# 文件上传相关
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB
ALLOWED_FILE_EXTENSIONS = ['.csv', '.xlsx', '.json', '.txt']
UPLOAD_CHUNK_SIZE = 8192  # 8KB

# 会话相关
SESSION_TIMEOUT = 3600  # 1小时
TOKEN_EXPIRY = 86400    # 24小时
REFRESH_TOKEN_EXPIRY = 604800  # 7天

# 限流相关
DEFAULT_RATE_LIMIT = 100  # 每分钟请求数
BURST_RATE_LIMIT = 200
RATE_LIMIT_WINDOW = 60  # 秒

# 日志相关
LOG_MAX_SIZE = 100 * 1024 * 1024  # 100MB
LOG_BACKUP_COUNT = 5
LOG_ROTATION_INTERVAL = 'midnight'

# 监控相关
METRICS_COLLECTION_INTERVAL = 60  # 秒
HEALTH_CHECK_ENDPOINT_TIMEOUT = 5  # 秒
ALERT_COOLDOWN_PERIOD = 300  # 5分钟

# 系统标识
SYSTEM_NAME = "VnPy Web"
SYSTEM_VERSION = "1.0.0"
API_VERSION = "v1"

# 加密相关
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
BCRYPT_ROUNDS = 12

# 数据精度
PRICE_PRECISION = 8
VOLUME_PRECISION = 4
PERCENTAGE_PRECISION = 4

# 字符串长度限制
MAX_NAME_LENGTH = 100
MAX_DESCRIPTION_LENGTH = 500
MAX_COMMENT_LENGTH = 1000
MAX_SYMBOL_LENGTH = 20

# 时间格式
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"
ISO_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
