# VnPy Web 统一配置文件
# 生成时间: 2025-08-21T06:24:01.627758

# === 应用配置 ===
APP_NAME=VnPy Web
APP_VERSION=1.0.0
HOST=0.0.0.0
PORT=8000
ENVIRONMENT=development
DEBUG=true

# === 数据库配置 ===
DB_TYPE=mysql
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=root
DB_NAME=vnpy

# === Redis配置 ===
REDIS_URL=redis://localhost:6379/0
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DB=0

# === JWT配置 ===
JWT_SECRET_KEY=jwt-secret-key
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30

# === 服务端口配置 ===
VNPY_CORE_PORT=8006
USER_TRADING_PORT=8001
STRATEGY_DATA_PORT=8002
GATEWAY_PORT=8004
MONITOR_PORT=8005
SERVICE_HOST=0.0.0.0
API_HOST=127.0.0.1

# === 路径配置 ===
DATA_DIR=./data
LOGS_DIR=./logs
TEMP_DIR=./temp
UPLOADS_DIR=./uploads
VNPY_DATA_DIR=./vnpy_data
VNPY_CONFIG_DIR=./vnpy_config