database:
  main:
    host: ${REDFIRE_SHARED_DB_HOST:localhost}
    port: ${REDFIRE_SHARED_DB_PORT:5432}
    name: ${REDFIRE_SHARED_DB_NAME:redfire_main}
    user: ${REDFIRE_SHARED_DB_USER:redfire}
    password: ${REDFIRE_SHARED_DB_PASSWORD:password}
    pool_size: 50
    max_overflow: 20
    echo: ${REDFIRE_SHARED_DB_ECHO:false}
    
  trading:
    host: ${REDFIRE_SHARED_TRADING_DB_HOST:localhost}
    port: ${REDFIRE_SHARED_TRADING_DB_PORT:5432}
    name: ${REDFIRE_SHARED_TRADING_DB_NAME:trading_data}
    user: ${REDFIRE_SHARED_TRADING_DB_USER:trading}
    password: ${REDFIRE_SHARED_TRADING_DB_PASSWORD:password}
    pool_size: 30
    max_overflow: 10
    
  timeseries:
    host: ${REDFIRE_SHARED_TIMESERIES_DB_HOST:localhost}
    port: ${REDFIRE_SHARED_TIMESERIES_DB_PORT:8086}
    name: ${REDFIRE_SHARED_TIMESERIES_DB_NAME:market_data}
    user: ${REDFIRE_SHARED_TIMESERIES_DB_USER:influx}
    password: ${REDFIRE_SHARED_TIMESERIES_DB_PASSWORD:password}
    
connection_pools:
  max_connections_per_pool: 100
  connection_timeout: 30
  idle_timeout: 300
  
migrations:
  auto_migrate: ${REDFIRE_SHARED_DB_AUTO_MIGRATE:true}
  migration_path: migrations/
  backup_before_migrate: true
