# RedFire 配置文件
# 基于您的 MySQL 数据库配置

# 应用基础配置
app_name: "RedFire"
app_version: "2.0.0"
environment: "development"
debug: true
host: "0.0.0.0"
port: 8000
workers: 1

# 安全配置
secret_key: "redfire-secret-key-dev-2024"
jwt_secret_key: "redfire-jwt-secret-key-dev-2024"
jwt_algorithm: "HS256"
jwt_access_token_expire_minutes: 30
jwt_refresh_token_expire_days: 30

# 数据库配置 - 使用您的 MySQL vnpy 数据库
# 请根据您的实际MySQL密码修改下面的配置
database_url: "mysql+pymysql://root:root@localhost:3306/vnpy"
db_echo: false
db_pool_size: 10
db_max_overflow: 20

# Redis配置
redis_url: "redis://localhost:6379/0"

# CORS配置
cors_origins:
  - "http://localhost:3000"
  - "http://127.0.0.1:3000"
  - "http://localhost:5173"
  - "http://127.0.0.1:5173"
cors_allow_credentials: true
cors_allow_methods:
  - "GET"
  - "POST"
  - "PUT"
  - "DELETE"
  - "OPTIONS"
  - "PATCH"
cors_allow_headers: ["*"]

# 目录配置
data_dir: "./data"
log_dir: "./logs"
temp_dir: "./temp"
upload_dir: "./uploads"

# VnPy配置
vnpy_data_dir: "./vnpy_data"
vnpy_log_dir: "./vnpy_logs"
vnpy_config_dir: "./vnpy_config"

# 日志配置
log_level: "INFO"
log_format: "json"

# 性能配置
max_connections: 100
request_timeout: 30

# 微服务配置
services:
  user_trading:
    name: "用户交易服务"
    port: 8001
    description: "用户认证、账户管理、订单交易、风险控制"
  
  vnpy_core:
    name: "VnPy核心交易引擎服务"
    port: 8006
    description: "VnPy核心交易引擎"
  
  strategy_data:
    name: "策略数据服务"
    port: 8002
    description: "策略管理和历史数据服务"
  
  gateway:
    name: "网关适配服务"
    port: 8004
    description: "交易网关适配服务"
  
  monitor:
    name: "监控通知服务"
    port: 8005
    description: "系统监控和通知服务"
